name: CI

on:
    pull_request:
        branches:
            - main
            - v*.x
    push:
        branches:
            - main
            - v*.x
    merge_group: {}

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
              with:
                    fetch-depth: 0

            - uses: pnpm/action-setup@0e279bb959325dab635dd2c09392533439d90093 # v6.0.8

            - uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6.1.0
              with:
                node-version-file: '.nvmrc'
                registry-url: 'https://registry.npmjs.org'
                cache: pnpm
            
            - name: Install
              run: pnpm install

            - name: Build
              run: pnpm build
            
            - name: Lint
              run: pnpm lint

            - name: Lint dependencies
              run: pnpm lint:dependencies

            - name: Lint package
              run: pnpm lint:packages

            - name: Lint types
              run: pnpm lint:types

            - name: Lint spell
              run: pnpm lint:spell
            
            - name: Test
              run: pnpm coverage

            - name: Typecheck
              run: pnpm typecheck
            